name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022 #possible variants: windows-2019, windows-2022, windows-2025(windows-latest)

    steps:
    - uses: actions/checkout@v4

  #  - name: Add MSBuild to PATH
  #    uses: microsoft/setup-msbuild@v1.0.2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DSKIP_TESTS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/serial_notifier_tests.exe

    - name: Archive production artifact
      uses: actions/upload-artifact@v4
      with:
        name: serial_notifier.exe
        path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/*.exe
