name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: windows-2022 #possible variants: windows-2019, windows-2022, windows-2025(windows-latest)
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -A Win32 -Wno-dev

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/serial_notifier.exe

    - name: Archive tests
      uses: actions/upload-artifact@v4
      with:
        name: tests
        path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/serial_notifier_tests.exe
        
  test:
    name: Test
    needs: build
    runs-on: windows-latest
    steps:    
      - name: Download tests binary
        uses: actions/download-artifact@v4
        with:
          name: tests
          
      - name: Run tests
        run: ${{github.workspace}}/serial_notifier_tests.exe -d yes
